<?php namespace JF;
/**

Copyright 2021 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-2e62ff
Date:    2021-04-26 06:55:15
Version: v3.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-2e62ff",
    "email": {
        "to": "jemlaleffe59@gmail.com",
        "cc": "Nom",
        "bcc": "Champ requis",
        "subject": "Formulaire de contact Peppers MArketing",
        "template": "",
        "fromName": "3"
    },
    "admin": {
        "users": "admin:0865b",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "http:\/\/maquette.peppers.marketing\/",
        "message": "Votre demande \u00e0 bien \u00e9t\u00e9 prise en compte. Notre \u00e9quipe vous contactera sous 48h. Vous allez être redirigé vers la page d'accueil",
        "seconds": "15"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "jemlaleffe59@gmail.com",
        "template": "",
        "replyTo": "Formulaire de contact site Peppers Marketing"
    },
    "seo": {
        "trackerId": "5",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "Please enter at least {0} characters.",
        "user": "Saisissez votre nom ...",
        "password": ""
    },
    "mailgun": {
        "domain": "Please enter no more than {0} characters.",
        "apiKey": "Please enter the same value again.",
        "fromEmail": "glyphicon glyphicon-user",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "6LceXboaAAAAAAMcOoU49gewmDQYDUT8PefkbvYW"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Nom",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Champ requis"
                    }
                },
                "placeholder": "Saisissez votre nom ...",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Champ requis"
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-envelope",
                    "leftText": ""
                },
                "placeholder": "Saisissez votre Email ..."
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Message",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Champ requis"
                    }
                },
                "addon": {
                    "leftIcon": "glyphicon glyphicon-edit"
                },
                "placeholder": "Saisissez votre message ..."
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Envoyer",
                "icon": "",
                "checkRequiredFields": "Champ requis"
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": "",
    "lang": {
        "language": "fr"
    },
    "twilio": {
        "toPhone": "5"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class